# Credits to Turbowarp/GarboMuffin for this workflow

name: validation


on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Validate Lint Type
        run: npm run lint:type
        continue-on-error: true
      - name: Validate Lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Validate Format
        run: npm run lint:format
        
        
